name = "Offers Text"

uid = "4e991c28-d4dc-950e-2964-4b47a0401cbb039f58b1"

type = "theme"

[[extension.blocks]]
name = "Offers Content"
target = "section"
handle = "offers-text"
settings = "blocks/star_rating.liquid"

[[extension.blocks]]
name = "WhatsApp"
target = "section"
handle = "whatsapp"
settings = "blocks/whatsapp-widget.liquid"
